<?php

/* @var Uecommerce_Mundipagg_Helper_Data $helper */
$helper = Mage::helper('mundipagg');

if (Mage::registry('current_order')) {
    $_order = $this->getOrder();
}

if (Mage::registry('current_invoice')) {
    $_order = $this->getInvoice()->getOrder();
}

if (Mage::registry('current_shipment')) {
    $_order = $this->getShipment()->getOrder();
}

if (Mage::registry('current_creditmemo')) {
    $data = Mage::registry('current_creditmemo')->getData();

    $_order = Mage::getModel('sales/order')->load($data['order_id']);
}

$standard = Mage::getModel('mundipagg/standard');

?>
<div>
    <p>
        <?php
        $info = $this->getInfo();

        $errorCode = $info->getAdditionalInformation('ErrorCode');
        $errorDescription = $info->getAdditionalInformation('ErrorDescription');

        if ($errorCode >= 400 && $errorDescription) {
            echo "<b>[{$helper->__('Integration error')}]</b><br/>";
            echo "{$helper->__('Error code')}: {$errorCode}<br/>";
            echo "{$helper->__('Error description')}: {$errorDescription}<br/><br/>";
            return;
        }

        $PaymentMethod = $info->getAdditionalInformation('PaymentMethod');
        $integrationError = $info->getAdditionalInformation('IntegrationError');

        echo "{$helper->__('Method')}: {$helper->__($PaymentMethod)}<br/>";

        $orderKeys = (array)$orderKeys = $_order->getPayment()->getAdditionalInformation('OrderKey');
        $orderKeysQty = count($orderKeys);

        if ($orderKeysQty > 0) {
            if ($orderKeysQty == 1) {
                echo "{$helper->__('OrderKey')}: {$orderKeys[0]}<br>";
            } else {
                echo "{$helper->__('OrderKeys')}:<br>";

                foreach ($orderKeys as $orderKey) {
                    echo "$orderKey<br>";
                }

            }

            if ($OrderReference = $_order->getPayment()->getAdditionalInformation('OrderReference')):
                echo "{$helper->__('OrderReference')}: {$OrderReference}<br/>";
            endif;
        }

        $ccQty = 0;

        switch ($PaymentMethod){
            case 'mundipagg_creditcard' :
            case 'mundipagg_creditcardoneinstallment' :
                $installmentsNumber = '1x';
                $ccQty = 1;
                break;

            case 'mundipagg_twocreditcards' :

                $ccQty = 2;
                break;

            case 'mundipagg_boleto' :
                    if (version_compare(Mage::getVersion(), '1.5.0', '<')) {
                        $transactionType = 'payment';
                    } else {
                        $transactionType = Mage_Sales_Model_Order_Payment_Transaction::TYPE_ORDER;
                    }

                    $transaction = Mage::getModel('sales/order_payment_transaction')->getCollection()
                        ->addAttributeToFilter('order_id', array('eq' => $_order->getEntityId()))
                        ->addAttributeToFilter('txn_type', array('eq' => $transactionType))
                        ->addAttributeToFilter('is_closed', array('eq' => '1'));
                    $nossoNumero = '';
                    $barcode = '';

                    foreach ($transaction as $t) {
                        $t = $t->getData();
                        $txDetail = $t['additional_information'];

                        if (!empty($txDetail)) {
                            $nossoNumero = $txDetail['NossoNumero'];
                            $barcode = $txDetail['Barcode'];
                        }
                    }

                    $boletoUrl = $_order->getPayment()->getAdditionalInformation('BoletoUrl');
                    echo $helper->__('Nosso Número') . ": " . "<b>" . $nossoNumero . "</b><br>";
                    echo $helper->__('Código de Barras') . ":" . $barcode . "<br>";
                    echo "<a href='" . $boletoUrl . "' target='_blank'>" . $helper->__('Print boleto') . "</a><br>";

                break;

            case 'mundipagg_debit' :
                    $bankName = $this->getInfo()->getAdditionalInformation('BankName');
                    $bankPaymentDate = $this->getInfo()->getAdditionalInformation('BankPaymentDate');

                    if ($bankName) {
                        echo $helper->__('Banco');
                    } else {
                        echo $bankName;
                    }

                    if ($bankPaymentDate) {
                        echo $helper->__('Data de pagamento');
                    } else {
                        echo $bankPaymentDate;
                    }
            break;
        }

        if ($ccQty > 0) {
            for ($i = 1; $i <= $ccQty; $i++) {
                $authorizationCode = $this->getAuthorizationCode($i);
                $txnId = $this->getTransactionId($i);

                $brand = $this->getCcBrand($i);
                $maskedCreditCardNumber = $info->getAdditionalInformation($i . "_MaskedCreditCardNumber");
                $ccValue = $this->getCcValue($i);

                if ($PaymentMethod != 'mundipagg_creditcardoneinstallment') {
                    $installmentsNumber = $this->getInstallmentsNumber($ccQty, $i);
                }

                $acquireMessage = $info->getAdditionalInformation($i . "_AcquirerMessage");

                $NSU = $this->getInfo()->getAdditionalInformation("{$i}_UniqueSequentialNumber");

                echo "<p>";
                echo "{$helper->__('Credit card issuer')}: {$brand}<br/>";
                echo "{$helper->__('Masked number')}: {$maskedCreditCardNumber}<br/>";
                echo "{$helper->__('Amount')}: {$ccValue}<br/>";
                echo "{$helper->__('Installments')}: {$installmentsNumber}<br/>";
                echo "{$helper->__('Authorization code')}: {$authorizationCode}<br/>";
                echo "{$helper->__('Transaction ID')}: {$txnId}<br/>";
                echo "{$helper->__('NSU')}: {$NSU}<br/>";
                echo "{$helper->__('Acquirer message')}: {$acquireMessage}<br/>";
                echo "</p>";
            }
        }
    ?>
    </p>

</div>