
<?php
    $_coreHelper = $this->helper('core');
    $frequencyType = [
        'Daily' => 'Day',
        'Weekly' => 'Week',
        'Monthly' => 'Month',
        'Quarterly' => 'Quarter',
        'Biannual' => 'Semester',
        'Yearly' => 'Year'
    ];

    $parcelamento = $this->getParcelamento();
    $recurrence = $this->getMundipaggRecurrence();
    $recurrences = $this->getMundipaggRecurrences();
    $frequency = $this->getMundipaggFrequency();
    $recurrenceMix = $this->getMundipaggRecurrenceMix();
    $reurrenceDiscount = $this->getMundipaggRecurrenceDiscount();
    if ($recurrenceMix) {
        echo '<strong>' .
                'ou ' .
                $_coreHelper->formatPrice(($this->getPrice() / $recurrences)) .
                ' ' . $this->__('by') . ' ' .
                $recurrences . ' ' .
                $this->__($frequencyType[$frequency] .'s') .
            '</strong>'
            ;
    } elseif ($recurrence) {
        echo '<strong>/' . 
                strtolower($this->__($frequencyType[$frequency])) .
                ' ' . $this->__('by') . ' ' .
                $recurrences . ' ' .
                $this->__($frequencyType[$frequency] .'s') .
                ' ('
                    . $this->__('Total') . ' ' .
                    $_coreHelper->formatPrice(($this->getPrice() * $recurrences)) .
                ')' .
            '</strong>'
            ;
    } else {
        if (!empty($parcelamento)) {
            echo $this->__('ou') . ' '  . '<strong>' . $parcelamento . '</strong>';
        }
    }
?>
