<?php
$fcontrol = Mage::getStoreConfig('payment/mundipagg_standard/antifraud');
$antifraudProvider = Mage::getStoreConfig('payment/mundipagg_standard/antifraud_provider');

if ($fcontrol && $antifraudProvider == Uecommerce_Mundipagg_Model_Source_Antifraud::ANTIFRAUD_FCONTROL): ?>

	<!--	<script type="text/javascript" src="https://static.fcontrol.com.br/fingerprint/fcontrol.min-ed.js"></script>-->
	<script type="text/javascript">

		var customVars = new Object();

		if (typeof jQuery == 'undefined') {

			try {
				var jQueryObj = document.createElement('script');
				jQueryObj.type = 'text/javascript';
				jQueryObj.async = true;
				jQueryObj.src = 'https://code.jquery.com/jquery-1.12.4.min.js';
				jQueryObj.integrity = "sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=";
				jQueryObj.crossorigin = "anonymous";

				document.getElementsByTagName('body')[0].appendChild(jQueryObj);
			} catch (err) {
				console.log(err);
			}
		}

		jQuery(document).ready(function () {

			var execFp = function () {
				jQuery.ajax({
					method: 'POST',
					url: '/mundipagg/fcontrol/getConfig',
					success: function (data) {
						sendFp(data.key, data.sessionId);
					},
					error: function (err) {
					}
				});
			};

			var sendFp = function (key, sessionId) {
				try {

					var fp = new FcontrolFingerprint();
					fp.send(key, sessionId);

				} catch (err) {
					console.log(err);
				}
			};

			var reportError = function (message) {
				jQuery.ajax({
					method: 'POST',
					url: '/mundipagg/fcontrol/reportError',
					dataType: 'JSON',
					data: {message: message}
				});
			};

			if (typeof FcontrolFingerprint == 'undefined') {
				var fpObj = document.createElement('script');
				fpObj.type = 'text/javascript';
				fpObj.async = true;
				document.getElementsByTagName('body')[0].appendChild(fpObj);

				if (typeof FcontrolFingerprint == 'undefined') {
					reportError('Unable to import FControl fingerprint script');
					return;
				}

				execFp();
			}

		});

	</script>

<?php endif; ?>