<?php
$fcontrol = Mage::getStoreConfig('payment/mundipagg_standard/antifraud');
$antifraudProvider = Mage::getStoreConfig('payment/mundipagg_standard/antifraud_provider');
$environment = Mage::getStoreConfig('payment/mundipagg_standard/environment_fcontrol');

if ($environment == Uecommerce_Mundipagg_Model_Source_FControlEnvironment::SANDBOX) {
	$scriptUrl = 'https://static.fcontrol.com.br/fingerprint/hmlg-fcontrol-ed.min.js';
} else {
	$scriptUrl = 'https://static.fcontrol.com.br/fingerprint/fcontrol-min-ed.js';
}

if ($fcontrol && $antifraudProvider == Uecommerce_Mundipagg_Model_Source_Antifraud::ANTIFRAUD_FCONTROL): ?>

	<script type="text/javascript" src="<?php echo $scriptUrl; ?>"></script>
	<script type="text/javascript">
		//jQuery.jQuery.noConflict();

		jQuery(document).ready(function ($) {
			
			$.ajax({
				method: 'POST',
				url: '/mundipagg/fcontrol/getConfig',
				dataType: 'JSON'

			}).done(function (data) {
				var fp = new FcontrolFingerprint();
				fp.send(data.key, data.sessionId);
			});

			$(document).ajaxComplete(function (event, request, settings) {
				if (typeof settings.url != 'undefined') {
					if (settings.url.match(/\/fcontrol\/fingerprint\//)) {

						var logRequest = settings.data;
						var logResponse = request.responseText;
						var url = '/mundipagg/fcontrol/logFp';

						$.post(url, {event: 'request', data: logRequest}, function () {
							$.post(url, {event: 'response', data: logResponse});
						});
					}
				}

			});

			var reportError = function (message) {
				jQuery.ajax({
					method: 'POST',
					url: '/mundipagg/fcontrol/reportError',
					dataType: 'JSON',
					data: {message: message}
				});
			};

		});

	</script>

<?php endif; ?>