<?php

$fingerprintIsEnabled = Mage::getStoreConfig('payment/mundipagg_standard/fingerprint');

if (!$fingerprintIsEnabled) {
	return;
}

$fcontrol = Mage::getStoreConfig('payment/mundipagg_standard/antifraud');
$antifraudProvider = Mage::getStoreConfig('payment/mundipagg_standard/antifraud_provider');
$environment = Mage::getStoreConfig('payment/mundipagg_standard/environment_fcontrol');

if ($environment == Uecommerce_Mundipagg_Model_Source_FControlEnvironment::SANDBOX) {
	$scriptUrl = 'https://static.fcontrol.com.br/fingerprint/hmlg-fcontrol-ed.min.js';
} else {
	$scriptUrl = 'https://static.fcontrol.com.br/fingerprint/fcontrol-ed.min.js';
}

if ($fcontrol && $antifraudProvider == Uecommerce_Mundipagg_Model_Source_Antifraud::ANTIFRAUD_FCONTROL): ?>

	<script type="text/javascript" src="<?php echo $scriptUrl; ?>"></script>
	<script type="text/javascript" src="/js/uecommerce/jquery-3.1.0.min.js"></script>
	<script type="text/javascript" src="/js/uecommerce/fcontrol/fingerprint-fcontrol.js"></script>

<?php endif; ?>