<?php
$antifraud = Mage::getStoreConfig('payment/mundipagg_standard/antifraud');
$antifraudProvider = Mage::getStoreConfig('payment/mundipagg_standard/antifraud_provider');

if ($antifraud && $antifraudProvider == Uecommerce_Mundipagg_Model_Source_Antifraud::ANTIFRAUD_CLEARSALE): ?>

	<script type="text/javascript">

		var _csdp = _csdp || [];

		if (jQuery == 'undefined') {
			try {
				var jQueryObj = document.createElement('script');
				jQueryObj.type = 'text/javascript';
				jQueryObj.async = true;
				jQueryObj.src = 'https://code.jquery.com/jquery-1.12.4.min.js';
				jQueryObj.integrity = "sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=";
				jQueryObj.crossorigin = "anonymous";

				document.getElementsByTagName('body')[0].appendChild(jQueryObj);

			} catch (err) {
				console.log(err);
			}
		}

		jQuery(document).ready(function () {

			jQuery.ajax({
				metho: 'POST',
				url: '/mundipagg/clearsale/getConfig',
				success: function(data){
					console.log(data);
					setCsdp(data.entityId, data.app, data.sessionId);
				},
				error: function(err){
					console.log(err);
				}
			});
			
			var setCsdp = function(merchantKeyOnAntiFraud, App, sessionId){
				_csdp.push(['Key', merchantKeyOnAntiFraud]);
				_csdp.push(['App', App]);
				_csdp.push(['SessionID', sessionId]);

				console.log(_csdp);

				(function () {
					var csd = document.createElement('script');

					csd.type = 'text/javascript';
					csd.async = true;
					csd.src = 'https://device.clearsale.com.br/profiler/fp.js';

					var sc = document.getElementsByTagName('script')[0];
					sc.parentNode.insertBefore(csd, sc);
				})();
					
			};

		});

	</script>

<?php endif; ?>